#!/usr/bin/env python

from __future__ import print_function, division
import sys
import itertools as it

import parser
import dataset
import logic

try: range = xrange
except: pass

def main (argv=None):
    if not argv: argv = sys.argv

    if len(argv) < 2:
        print("Dataset file required", file=sys.stderr);
        return 1;

    try:
        f = open(argv[1], "rt");
        problem = parser.run(f, dataset.ProblemStructure)

        logic.run(problem)
    except KeyboardInterrupt:
        print("Interrupted. BYE!", file=sys.stderr)
        return 1
    finally:
        f.close()

    return 0

if __name__ == "__main__":
    sys.exit(main())

